### PR TITLE
entrypoint: support multiple colon-separated plot directories

### PR DESCRIPTION
**Pull request by 7AC**
fixes https://github.com/Chia-Network/chia-docker/issues/44

### CODE REVIEW

**Comment by zhirschtritt** [comment]
I did something similar locally to get around this, so I'm all for this change. I think it would be better if it weren't a *breaking* change though. Maybe keep the `plot_dir` arg as is so folks can still pull the latest image without it breaking their current build and just allow it to accept comma separated paths?

**Review by zhirschtritt — APPROVED** [review]

**Review by Gnomuz — DISMISSED** [review]
Definitely needed by whoever has more than a single directory to store plots, reminded that even subdirectories have to be specified explicitly.

**Review by justinengland — APPROVED** [review]
i am not convinced this is a more stable solution.

**Comment by justinengland** [comment]
and yes. I will have to kick off a build to release these updates

**Pull request merged**
