### PR TITLE
Revised log to stdout and upnp configuration

### PR DESCRIPTION
**Pull request by daneget**
This PR has two enhacements:

- The log output has been configured to avoid the creation of a log file
- Added new environment variable to enable or disable upnp flag, which has false value by default

### CODE REVIEW

**Comment by Artanicus** [comment]
LGTM. If the logging change seems too drastic, then #122 would be a more minimal change to get logging to function correctly right now instead of logs to stdout "freezing" over time due to log rotation.

Huge +1 on the UPnP default.

**Comment by cmmarslender** [comment]
My only concern with logging to stdout only is if someone is running this with another sidecar for something that parses the logs and expects an actual file (chiadog, etc)

**Comment by daneget** [comment]
With the last change I made logging to stdout or to file configurable, so if someone needs to parse logs files now it's possible

**Review by cmmarslender — APPROVED** [review]

**Comment by cmmarslender** [comment]
@daneget note that another PR was just merged to swap the upnp/log stdout to the opposite default values to retain back-compat with how this previously functioned. You'll need to set those to false if you want to use the new behaviors that were introduced in this PR

**Pull request merged**
